/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSeriesInfoRouteImport } from './routes/api/series-info'
import { Route as ApiM3uRouteImport } from './routes/api/m3u'
import { Route as ApiEpgRouteImport } from './routes/api/epg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesInfoRoute = ApiSeriesInfoRouteImport.update({
  id: '/api/series-info',
  path: '/api/series-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiM3uRoute = ApiM3uRouteImport.update({
  id: '/api/m3u',
  path: '/api/m3u',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpgRoute = ApiEpgRouteImport.update({
  id: '/api/epg',
  path: '/api/epg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/epg': typeof ApiEpgRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/series-info': typeof ApiSeriesInfoRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/epg': typeof ApiEpgRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/series-info': typeof ApiSeriesInfoRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/epg': typeof ApiEpgRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/series-info': typeof ApiSeriesInfoRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/epg' | '/api/m3u' | '/api/series-info' | '/api/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/epg' | '/api/m3u' | '/api/series-info' | '/api/stream'
  id:
    | '__root__'
    | '/'
    | '/api/epg'
    | '/api/m3u'
    | '/api/series-info'
    | '/api/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEpgRoute: typeof ApiEpgRoute
  ApiM3uRoute: typeof ApiM3uRoute
  ApiSeriesInfoRoute: typeof ApiSeriesInfoRoute
  ApiStreamRoute: typeof ApiStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series-info': {
      id: '/api/series-info'
      path: '/api/series-info'
      fullPath: '/api/series-info'
      preLoaderRoute: typeof ApiSeriesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/m3u': {
      id: '/api/m3u'
      path: '/api/m3u'
      fullPath: '/api/m3u'
      preLoaderRoute: typeof ApiM3uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/epg': {
      id: '/api/epg'
      path: '/api/epg'
      fullPath: '/api/epg'
      preLoaderRoute: typeof ApiEpgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEpgRoute: ApiEpgRoute,
  ApiM3uRoute: ApiM3uRoute,
  ApiSeriesInfoRoute: ApiSeriesInfoRoute,
  ApiStreamRoute: ApiStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
