/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiM3uRouteImport } from './routes/api/m3u'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiM3uRoute = ApiM3uRouteImport.update({
  id: '/api/m3u',
  path: '/api/m3u',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/m3u': typeof ApiM3uRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/m3u' | '/api/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/m3u' | '/api/stream'
  id: '__root__' | '/' | '/api/m3u' | '/api/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiM3uRoute: typeof ApiM3uRoute
  ApiStreamRoute: typeof ApiStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/m3u': {
      id: '/api/m3u'
      path: '/api/m3u'
      fullPath: '/api/m3u'
      preLoaderRoute: typeof ApiM3uRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiM3uRoute: ApiM3uRoute,
  ApiStreamRoute: ApiStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
